### ISSUE TITLE
chore: improve tooling for local development

### ISSUE THREAD

**Issue by mariz-ov** [pixelaw/game#3]
#### Description
Currently, when the World Address changes or the prefunded accounts change, a lot of things are affected e.g. the environment variables for the web directory, the bots directory and etc. To make it easier for other developers, local development tools become necessary.

#### Tasks
- [x] Get Prefunded Accounts when Katana starts running
- [x] Replace environment variables for Prefunded Accounts - /web/.env, /contracts/Scarb.toml, /bots/.env
- [x] Get deployed World Address from sozo migrate
- [x] Replace environment variables - /web/.env, /contracts/Scarb.toml, /bots/.env

**Comment by mariz-ov** [comment]
Now merged on dev and master. No issues so far
