### ISSUE TITLE
refactor: pixel rendering when playing

### ISSUE THREAD

**Issue by mariz-ov** [pixelaw/game#6]
#### Description
When scrolling horizontally or vertically in the pixels page, it should automatically refetch the state of the pixels the user should be seeing. Right now it's getting a preset amount of pixels instead of offsetting according to a user's current location in the board.

#### Files
/web/src/hooks/usePaintedPixels.ts
/web/src/components/Main.tsx

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Calculate the offset from the scroll
- [ ] Refactor usePaintedPixels to get only the necessary pixels
- [ ] Remake the Main component and its children to allow scrolling and positioning calculation
