### ISSUE TITLE
feat: view state of all the pixels

### ISSUE THREAD

**Issue by mariz-ov** [pixelaw/game#7]
#### Description
In the lobby page, a placeholder image of all the pixels are put in. The placeholder should be replaced by the current state of the pixels. To do so, a simple bot (written in NodeJS) that queries torii can be made to get the view of the entire board, draws them, and then saves the drawing into PNG. The PNG is then sent to a CDN and the placeholder image's src should be replaced with that drawn image.

#### Files
/web/src/pages/LobbyScreen.tsx

#### Tasks
- [x] Get current state of the pixels
- [x] Draw the board
- [x] Save board to PNG
- [x] Send board to a CDN
- [x] Loop process
- [x] Change src in the LobbyScreen to point to the uploaded PNG file
