### ISSUE TITLE
feat: notify users of things to do

### ISSUE THREAD

**Issue by mariz-ov** [pixelaw/game#8]
#### Description
Users need to be able to react to an event if that user's attention is necessary e.g. a user needs to reveal his or her choice in rock, paper, scissors. The solution was to create a Notification Event that is emitted by a Game. That Notification Event is then indexed (by Torii if it's possible or through another bot) and presented on the UI.

#### Files
/web/src/components/Notification.tsx

#### Tasks
- [x] Create NeedsAttention component
- [x] Get all NeedsAttention for an owner
- [x] Add Notifs to the Notifications Panel
- [x] POC for NeedsAttention usage

**Comment by mariz-ov** [comment]
Changing the deliverables:

To notify for an event in a pixel, pixel app developers set NeedsAttention to true for a certain pixel. The UI will handle notifying user based on pixels from NeedsAttention. Also offloading setting it back to false to pixel app developers.

**Comment by mariz-ov** [comment]
After the bot, executes the scheduled remove_color. instead of removing ownership, it will set NeedsAttention
